# Generated by Django 3.1.2 on 2021-01-25 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('departamento', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('creado', models.DateField(null=True)),
                ('codigo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion', models.ManyToManyField(to='Tramites.Notificacion')),
                ('roles', models.ManyToManyField(to='Tramites.Rol')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TramitePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('iniciado', models.DateField(null=True)),
                ('terminado', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estados', models.ManyToManyField(null=True, to='Tramites.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(null=True)),
                ('fecha_limite', models.DateField(null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tramites.documento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(null=True)),
                ('a_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rol_a_cargo', to=settings.AUTH_USER_MODEL)),
                ('peticionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno_peticionante', to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tramites.tipotramite')),
            ],
        ),
        migrations.CreateModel(
            name='Pase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(null=True)),
                ('fin', models.DateField(null=True)),
                ('notificacion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tramites.notificacion')),
                ('peticion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tramites.peticion')),
                ('proximo_estado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tramites.estado')),
                ('requerimientos', models.ManyToManyField(blank=True, null=True, to='Tramites.Requerimiento')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='a_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tramites.rol'),
        ),
        migrations.AddField(
            model_name='estado',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
