# Generated by Django 3.1.6 on 2021-02-05 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.IntegerField(null=True)),
                ('notificaciones', models.ManyToManyField(to='Tramites.Notificacion')),
            ],
        ),
        migrations.CreateModel(
            name='TramiteSolicitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado', models.DateField(null=True)),
                ('terminado', models.DateField(blank=True, null=True)),
                ('en_proceso', models.BooleanField(null=True)),
                ('finalizado', models.BooleanField(null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estados', models.ManyToManyField(to='Tramites.Estado')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='notificacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='codigo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tipotramite',
            name='requerimientos',
            field=models.ManyToManyField(to='Tramites.Requerimiento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pase',
            name='requerimientos',
            field=models.ManyToManyField(blank=True, to='Tramites.Requerimiento'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='departamento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tipotramite',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TramitePedido',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='tramitesolicitado',
            name='tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tramites.tipotramite'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='Tramites.Rol'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
